apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtmyt6633-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtmyt6633-tenant-component
    app.kubernetes.io/part-of: loadtmyt6633-tenant-app
  name: loadtmyt6633-tenant-component
  namespace: loadtmyt6633-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtmyt6633-tenant-component
    weight: null
status: {}
